version: 2.1

executors:
  node_latest:
    docker:
    - image: circleci/node:latest
  node_lts:
    docker:
      - image: circleci/node:lts
  default_executor: node_latest

aliases:
  - &repo_path
    ~/monorepo
  - &defaults
    working_directory: *repo_path
  - &yarn_cache_key
    yarn-sha-{{ checksum "yarn.lock" }}
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /release\/.*/
  - &execute_on_release
    filters:
      tags:
        only: /v?[0-9]+(\.[0-9]+)*/
      branches:
        ignore:
          - /.*/
  - &execute_on_release_prerelease
    filters:
      tags:
        only: /v?[0-9]+(\.[0-9]+)*([-+][a-zA-Z0-9]+)+([-+\.][a-zA-Z0-9-]+)*/
      branches:
        ignore:
          - /.*/

commands:
  restore_repo:
    description: Restore repository from workspace
    steps:
      - attach_workspace:
          at: *repo_path

jobs:
  prepare:
    <<: *defaults
    executor: default_executor
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install monorepo dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build projects
          command: yarn build
      - save_cache:
          key: *yarn_cache_key
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: *repo_path
          paths:
            - ./*

  lint:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: Lint code
          command: yarn lint

  test_node_latest:
    <<: *defaults
    executor: node_latest
    steps:
      - restore_repo
      - run:
          name: Test with Node (Latest)
          command: yarn test
      - run:
          name: Publish coverage
          command: yarn coverage:publish

  test_node_lts:
    <<: *defaults
    executor: node_lts
    steps:
      - restore_repo
      - run:
          name: Test with Node (LTS)
          command: yarn test

  test_publish:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: 'Publish canary version in a Verdaccio in memory'
          command: |
            export YARN_CONFIG_PREFIX="/tmp/yarn-global"
            mkdir $YARN_CONFIG_PREFIX
            yarn config set prefix $YARN_CONFIG_PREFIX
            export PATH="$PATH:$YARN_CONFIG_PREFIX/bin"
            preid=$(echo $CIRCLE_BRANCH | sed -r 's/[^[:alpha:][:digit:]]+/-/g')
            yarn global add verdaccio verdaccio-auth-memory verdaccio-memory nohup npm-auth-to-token
            tmp_registry_log=`mktemp`
            nohup verdaccio -c verdaccio.yml 2>&1 &>$tmp_registry_log &
            grep -q 'http address' <(tail -f $tmp_registry_log)
            npm-auth-to-token -u user -p test -e test@test.com -r http://localhost:4873
            yarn publish:canary --yes --no-push --preid=$preid --registry=http://localhost:4873

  publish:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: 'Setup publish credentials'
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish
          command: yarn release:publish --yes --registry=https://registry.npmjs.org

  publish_prerelease:
    <<: *defaults
    executor: default_executor
    steps:
      - restore_repo
      - run:
          name: 'Setup publish credentials'
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish prerelease
          command: yarn release:publish-prerelease --yes --registry=https://registry.npmjs.org

workflows:
  version: 2
  workflow:
    jobs:
      - prepare:
          <<: *ignore_non_dev_branches
      - lint:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_node_latest:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_node_lts:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_publish:
          requires:
            - lint
            - test_node_latest
            - test_node_lts
          <<: *ignore_non_dev_branches
      - publish:
          requires:
            - test_publish
          <<: *execute_on_release
      - publish_prerelease:
          requires:
            - test_publish
          <<: *execute_on_release_prerelease
